const placeholderData = [
  { id: "tilePlaceholder_1",
    tileHeadline: "Article 1",
    previewHeadline: "Article One"},
  { id: "tilePlaceholder_2",
    tileHeadline: "Article 2",
    previewHeadline: "Article Two"},
  { id: "tilePlaceholder_3",
    tileHeadline: "Article 3",
    previewHeadline: "Article Three"},
  { id: "tilePlaceholder_4",
    tileHeadline: "Article 4",
    previewHeadline: "Article Four"},
  { id: "tilePlaceholder_5",
    tileHeadline: "Article 5",
    previewHeadline: "Article Five"},
  { id: "tilePlaceholder_6",
    tileHeadline: "Article 6",
    previewHeadline: "Article Six"},
  { id: "tilePlaceholder_7",
    tileHeadline: "Article 7",
    previewHeadline: "Article Seven"},
  { id: "tilePlaceholder_8",
    tileHeadline: "Article 8",
    previewHeadline: "Article Eight"},
  { id: "tilePlaceholder_9",
    tileHeadline: "Article 9",
    previewHeadline: "Article Nine"},
]

export default placeholderData
