const placeholderData = [
  { id: "cardPlaceholder_1",
    tileHeadline: "External Demo 1",
    previewHeadline: "External Demo One",
    externalUrl: "https://somelink"},
  { id: "cardPlaceholder_2",
    tileHeadline: "External Demo 2",
    previewHeadline: "External Demo Two",
    externalUrl: "https://somelink"},
  { id: "cardPlaceholder_3",
    tileHeadline: "External Demo 3",
    previewHeadline: "External Demo Three",
    externalUrl: "https://somelink"},
  { id: "cardPlaceholder_4",
    tileHeadline: "External Demo 4",
    previewHeadline: "External Demo Four",
    externalUrl: "https://somelink"},
  { id: "cardPlaceholder_5",
    tileHeadline: "External Demo 5",
    previewHeadline: "External Demo Five",
    externalUrl: "https://somelink"},
  { id: "cardPlaceholder_6",
    tileHeadline: "External Demo 6",
    previewHeadline: "External Demo Six",
    externalUrl: "https://somelink"},
];

export default placeholderData;
